#!/usr/bin/env bash
# AI-attribution guard — blocks tool-authorship tells from leaking into commits.
# SEPARATE from forbidden-words.sh (voice); this is provenance hygiene, not a
# VOICE.md rule. Deliberately does NOT ban the bare tokens "AI"/"Claude":
# VOICE.md ships "AI concierge" (line 32) and packages/ai is a real path. Only
# explicit authorship-attribution phrases are blocked.
#
# Usage: no-ai-attribution.sh [file...]   # staged files, or the commit-msg file
#
# Optional stricter phrases you may add to PAT later: "ai-generated",
# the "🤖" trailer emoji, "generated by claude".
set -eo pipefail

PAT='co-authored-by:.*(claude|anthropic)|generated with claude|\bas an ai (language model|assistant)\b'

[ "$#" -gt 0 ] || { echo "ai-attribution guard: no files"; exit 0; }

fail=0
for f in "$@"; do
  [ -f "$f" ] || continue
  # Skip this guard's own source — it necessarily contains the literal patterns.
  case "$f" in */no-ai-attribution.sh|no-ai-attribution.sh) continue ;; esac
  hits=$(grep -inIE "$PAT" "$f" || true)
  if [ -n "$hits" ]; then
    echo "AI-ATTRIBUTION in $f:"
    echo "$hits" | sed 's/^/  /'
    fail=1
  fi
done

[ "$fail" -eq 0 ] && echo "ai-attribution guard: clean"
exit "$fail"
